# Generated by Django 5.1.1 on 2024-11-19 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StepByStep',
            fields=[
                ('id_paso', models.AutoField(primary_key=True, serialize=False, verbose_name='ID del Paso')),
                ('pasos', models.TextField(verbose_name='Descripción del Paso')),
            ],
        ),
        migrations.CreateModel(
            name='FunctionalTest',
            fields=[
                ('functional_test_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID de la Prueba Funcional')),
                ('url', models.URLField(max_length=2048, verbose_name='URL de la Prueba Funcional')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='functional_tests', to='user_projects.project', verbose_name='Proyecto Asociado')),
            ],
            options={
                'verbose_name': 'Prueba Funcional',
                'verbose_name_plural': 'Pruebas Funcionales',
            },
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('action_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID de la Acción')),
                ('action', models.CharField(max_length=255, verbose_name='Acción')),
                ('element_type', models.CharField(max_length=100, verbose_name='Tipo de Elemento')),
                ('value', models.CharField(blank=True, max_length=255, null=True, verbose_name='Valor')),
                ('input_value', models.CharField(blank=True, max_length=255, null=True, verbose_name='Valor de Entrada')),
                ('functional_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='ai_module.functionaltest', verbose_name='Prueba Funcional')),
                ('paso_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ai_module.stepbystep', verbose_name='ID del Paso Asociado')),
            ],
            options={
                'verbose_name': 'Acción',
                'verbose_name_plural': 'Acciones',
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('test_case_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID del Caso de Prueba')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del Caso de Prueba')),
                ('url', models.URLField(max_length=2048, verbose_name='URL del Caso de Prueba')),
                ('resultado_esperado', models.TextField(verbose_name='Resultado Esperado')),
                ('functional_test_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ai_module.functionaltest')),
            ],
            options={
                'verbose_name': 'Caso de Prueba',
                'verbose_name_plural': 'Casos de Prueba',
            },
        ),
        migrations.AddField(
            model_name='stepbystep',
            name='test_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='ai_module.testcase', verbose_name='Caso de Prueba Asociado'),
        ),
    ]
