# Generated by Django 5.1.1 on 2024-10-28 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_module', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='document_type',
        ),
        migrations.AlterField(
            model_name='testcase',
            name='actions_data',
            field=models.TextField(verbose_name='Actions Data'),
        ),
    ]
