# Generated by Django 5.1.1 on 2024-11-22 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_module', '0002_testcase_use_id_alter_testcase_functional_test_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='paso_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_module.stepbystep'),
        ),
    ]
