# Generated by Django 5.1.1 on 2024-11-09 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ai_module", "0003_testcase_a"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testcase",
            name="a",
        ),
    ]
