# Generated by Django 5.1.1 on 2024-11-09 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_module", "0004_remove_testcase_a"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testcase",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
