# Generated by Django 5.1.1 on 2024-11-07 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_projects', '0003_alter_project_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rojects', to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
    ]
