# Generated by Django 5.1.1 on 2024-11-09 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_projects", "0004_alter_project_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
