# Generated by Django 5.1.1 on 2024-11-19 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20, verbose_name='Estado')),
                ('description', models.CharField(max_length=255, verbose_name='Descripción')),
                ('evidence', models.CharField(blank=True, max_length=255, null=True, verbose_name='Evidencia')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='ai_module.action', verbose_name='Acción Asociada')),
            ],
            options={
                'verbose_name': 'Resultado',
                'verbose_name_plural': 'Resultados',
            },
        ),
    ]
