# Generated by Django 5.1.1 on 2024-10-28 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('functional_tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='functionaltest',
            options={'verbose_name': 'Functional Test', 'verbose_name_plural': 'Functional Tests'},
        ),
        migrations.RemoveField(
            model_name='functionaltest',
            name='execution',
        ),
        migrations.RemoveField(
            model_name='functionaltest',
            name='result',
        ),
    ]
