# Generated by Django 5.1.1 on 2024-11-09 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("functional_tests", "0002_alter_functionaltest_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="functionaltest",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
